import { supabase } from './supabase';import type { Contract,Show } from './driverData';import type { Profile } from '../types'
export type DashboardStats={shows:number;unsigned:number;reviews:number;drivers:number;feedback:number}
export async function getDashboardStats(){const today=new Date().toISOString().slice(0,10);const [shows,unsigned,reviews,drivers,feedback]=await Promise.all([supabase.from('shows').select('*',{count:'exact',head:true}).gte('ends_on',today),supabase.from('contracts').select('*',{count:'exact',head:true}).is('signed_at',null),supabase.from('contracts').select('*',{count:'exact',head:true}).in('status',['submitted','under_review']),supabase.from('profiles').select('*',{count:'exact',head:true}).eq('role','driver').eq('is_active',true),supabase.from('feedback').select('*',{count:'exact',head:true}).eq('status','new')]);return {shows:shows.count||0,unsigned:unsigned.count||0,reviews:reviews.count||0,drivers:drivers.count||0,feedback:feedback.count||0} as DashboardStats}
export async function getShowsAdmin(){const {data,error}=await supabase.from('shows').select('*,contracts(id,kind,status,driver_id)').order('starts_on',{ascending:false});if(error)throw error;return data as (Show&{contracts:{id:string;kind:string;status:string;driver_id:string|null}[]})[]}
export async function createShow(input:Omit<Show,'id'|'details_unlock_at'>){const {error}=await supabase.from('shows').insert({...input,details_unlock_at:new Date(new Date(`${input.starts_on}T12:00:00`).getTime()-3*864e5).toISOString()});if(error)throw error}
export async function getDrivers(){const {data,error}=await supabase.from('profiles').select('id,full_name,avatar_url,phone,role,is_active').order('full_name');if(error)throw error;return data as Profile[]}
export async function createContract(input:{show_id:string;driver_id:string|null;kind:'setup'|'teardown';contract_pay:number|null;bonus_pay:number|null}){const {data,error}=await supabase.from('contracts').insert({...input,status:'available'}).select('id').single();if(error)throw error;const {data:template}=await supabase.from('checklist_templates').select('id').eq('kind',input.kind).eq('active',true).order('version',{ascending:false}).limit(1).maybeSingle();if(template){const {error:assignError}=await supabase.rpc('admin_assign_checklist',{target_contract:data.id,target_template:template.id});if(assignError)throw assignError}}
export async function updateUser(id:string,role:'driver'|'admin',active:boolean){const {error}=await supabase.rpc('admin_update_user',{target_user:id,new_role:role,new_active:active});if(error)throw error}
export async function getReviews(){const {data,error}=await supabase.from('contracts').select('id,kind,status,submitted_at,admin_note,show:shows(*),driver:profiles!contracts_driver_id_fkey(id,full_name)').in('status',['submitted','under_review']).order('submitted_at');if(error)throw error;return data as unknown as (Contract&{submitted_at:string|null;driver:{id:string;full_name:string}})[]}
export async function reviewContract(id:string,approved:boolean,note:string){const {error}=await supabase.from('contracts').update({status:approved?'approved':'in_progress',reviewed_at:new Date().toISOString(),admin_note:note}).eq('id',id);if(error)throw error}
export async function getTemplates(){const {data,error}=await supabase.from('checklist_templates').select('id,name,kind,version,active,sections:checklist_sections(id,title,position,items:checklist_items(id,title,photo_required,required,position))').order('created_at',{ascending:false});if(error)throw error;return data||[]}
export async function createTemplate(name:string,kind:'setup'|'teardown',sections:{title:string;items:{title:string;photo_required:boolean}[]}[]){const {data,error}=await supabase.from('checklist_templates').insert({name,kind}).select('id').single();if(error)throw error;for(let s=0;s<sections.length;s++){const {data:section,error:se}=await supabase.from('checklist_sections').insert({template_id:data.id,title:sections[s].title,position:s}).select('id').single();if(se)throw se;if(sections[s].items.length){const {error:ie}=await supabase.from('checklist_items').insert(sections[s].items.map((i,p)=>({section_id:section.id,title:i.title,photo_required:i.photo_required,position:p})));if(ie)throw ie}}}
export async function getFeedback(){const {data,error}=await supabase.from('feedback').select('id,category,message,status,created_at,profile:profiles!feedback_submitted_by_fkey(full_name)').order('created_at',{ascending:false});if(error)throw error;return data||[]}
export async function getToolbags(){const {data,error}=await supabase.from('toolbags').select('id,number,notes,assigned_to,driver:profiles(full_name),items:toolbag_items(id,name,category)').order('number');if(error)throw error;return data||[]}
export async function createToolbag(number:string,driver:string|null){const {error}=await supabase.from('toolbags').insert({number,assigned_to:driver||null});if(error)throw error}
